### ISSUE TITLE
HI

### ISSUE THREAD

**Issue by qiurigao** [messi2050/android_device_lge_ph2n#2]
How to conversion the device tree from cm-13.0>>CM14.1 ?

**Comment by messi2050** [comment]
You mean how to create cm14.1 branch ?

**Comment by qiurigao** [comment]
@messi2050 NO ,is write device tree

**Comment by qiurigao** [comment]
i have cm-13.0 device tree ，How to conversion CM14.1 ？
https://github.com/qiurigao/android_device_vivo_pd1613

**Comment by messi2050** [comment]
May this help
https://forum.xda-developers.com/showthread.php?t=2010281

**Comment by qiurigao** [comment]
@messi2050  Thank you
